site_name: Guía de Redes

docs_dir: 'md'

site_dir: 'docs'

nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Conceptos:
      - Modelo OSI y TCP/IP: conceptos/modelos_osi_tcpip.md
      - Direccionamiento IP: conceptos/direccionamiento_ip.md
  - Ejemplos:
      - Configuraciones básicas: ejemplos/configuraciones_basicas.md
  - Herramientas: herramientas.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  collapse_navigation: true
  titles_only: false
  sticky_navigation: true
  locale: es

  logo: img/logo.png

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
