site_name: Guía de Redes

docs_dir: 'md'

site_dir: 'docs'

nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Conceptos:
      - Modelo OSI y TCP/IP: conceptos/modelos_osi_tcpip.md
      - Direccionamiento IP: conceptos/direccionamiento_ip.md
  - Ejemplos:
      - Configuraciones básicas: ejemplos/configuraciones_basicas.md
  - Herramientas: herramientas.md

theme:
  name: material
  highlightjs: true

  palette:
    - scheme: default
      primary: grey
      accent: blue-grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: grey
      accent: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - toc.integrate
    - search.suggest
    - search.highlight

extra:
  logo: img/logo.png
  favicon: img/favicon.png




markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
